const {chromium}=require('playwright');const assert=require('node:assert/strict');
const url=process.env.GATE_URL||'http://127.0.0.1:8765/gate/';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const errors=[];
 async function open(mobile=false){const context=await browser.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3}:{viewport:{width:1200,height:900}});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{Math.random=()=>.99;window.workerEvents=[];const Original=Worker;window.Worker=class extends Original{constructor(...args){super(...args);workerEvents.push('start');}terminate(){workerEvents.push('stop');super.terminate();}};});await p.goto(url);await p.waitForSelector('.gomoku-board');await p.waitForFunction(()=>document.querySelector('#game').dataset.phase==='human');return p;}
 const other=await browser.newPage();await other.addInitScript(()=>{Math.random=()=>0;});await other.goto(url);await other.waitForSelector('#dial');assert.ok(!(await other.evaluate(()=>performance.getEntriesByType('resource').map(x=>x.name))).some(x=>x.includes('/gomoku/worker.js')||x.includes('/gomoku/ai.js')||x.includes('/gomoku/vendor/')),'AI search payload stays lazy in other games');await other.close();
 const p=await open(),requests=[];p.on('request',r=>requests.push(r.url()));
 assert.equal(await p.locator('#game').getAttribute('data-game'),'gomoku');assert.ok(await p.locator('#target').isHidden());assert.equal(await p.locator('#target').textContent(),'');assert.ok(await p.locator('#enter').isDisabled());
 assert.deepEqual(await p.evaluate(()=>workerEvents),['start','stop']);assert.equal(await p.locator('.gomoku-cell[data-stone="2"]').count(),1,'Panda opens');
 await p.screenshot({path:'/tmp/gomoku-desktop.png'});
 await p.evaluate(()=>{for(const index of [113,114,115,113])document.querySelector(`[data-index="${index}"]`).click();});
 assert.equal(await p.locator('.gomoku-cell[data-stone="1"]').count(),1);await p.waitForFunction(()=>document.querySelector('#game').dataset.phase==='human');assert.equal(await p.locator('.gomoku-cell[data-stone="2"]').count(),2);assert.ok(await p.locator('#enter').isDisabled());
 await p.locator('[data-index="113"]').click();assert.equal(await p.locator('.gomoku-cell[data-stone="1"]').count(),1,'occupied click ignored');
 await p.locator('[data-index="113"]').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>document.activeElement.dataset.index),'114');await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('#game').dataset.phase==='human');assert.equal(await p.locator('.gomoku-cell[data-stone="1"]').count(),2);
 await p.screenshot({path:'/tmp/gomoku-play.png'});
 // Actual cloud-browser Worker request is delayed, then discarded after reset.
 let held,resolveHeld;const heldReady=new Promise(r=>resolveHeld=r);await p.route('**/gomoku/worker.js',route=>{held=route;resolveHeld();});
 await p.locator('[data-index="120"]').click();await heldReady;await p.locator('#new-target').click();assert.notEqual(await p.locator('#game').getAttribute('data-game'),'gomoku');await held.continue().catch(()=>{});await p.waitForTimeout(100);assert.equal(await p.locator('.gomoku-board').count(),0);assert.ok(await p.locator('#enter').isDisabled());
 assert.equal((await p.evaluate(()=>workerEvents)).filter(x=>x==='start').length,(await p.evaluate(()=>workerEvents)).filter(x=>x==='stop').length);
 // Worker load error gives Retry, never entry; retry restores normal play.
 const failed=await open();await failed.route('**/gomoku/worker.js',route=>route.abort());await failed.locator('[data-index="113"]').click();await failed.waitForFunction(()=>document.querySelector('#game').dataset.phase==='error');assert.ok(await failed.locator('#enter').isDisabled());assert.equal(await failed.locator('#rematch').innerText(),'Retry');await failed.unroute('**/gomoku/worker.js');await failed.locator('#rematch').click();await failed.waitForFunction(()=>document.querySelector('#game').dataset.phase==='human');assert.equal(await failed.locator('.gomoku-cell[data-stone="2"]').count(),2);
 // A fake asynchronous adapter isolates complete UI/entry/lifecycle outcomes.
 async function fixture(aiMoves,humanFirst=true){const page=await open();await page.evaluate(async({aiMoves,humanFirst})=>{
   const {createGomokuGame}=await import('/gate/games/gomoku/game.js');const {canEnter}=await import('/gate/common/engine.js');const {enterPersonal}=await import('/gate/common/entry.js');
   document.querySelector('#new-target').remove();const host=document.createElement('div');document.querySelector('main').replaceChildren(host);const enter=document.createElement('button');enter.id='fixture-enter';enter.textContent='Enter';enter.disabled=true;document.querySelector('main').append(enter);window.fixtureStates=[];window.cancelled=0;
   const engine={findMove:async()=>aiMoves.shift(),cancel(){window.cancelled++;},destroy(){}};const game=createGomokuGame(host,state=>{fixtureStates.push(state);enter.disabled=!canEnter(undefined,state,{humanVictory:true,requireStopped:true});},null,{engine,humanFirst});game.reset();window.fixtureGame=game;enter.onclick=()=>enterPersonal(undefined,game.getState(),{humanVictory:true,requireStopped:true});
 },{aiMoves,humanFirst});return page;}
 const winner=await fixture([30,32,34,36]);for(const index of [0,1,2,3,4]){await winner.locator(`[data-index="${index}"]`).click();await winner.waitForTimeout(0);}assert.equal(await winner.locator('#gomoku-status').textContent(),'You won.');assert.ok(await winner.locator('#fixture-enter').isEnabled());assert.equal(await winner.evaluate(()=>sessionStorage.getItem('personal-gate-pass')),null);await winner.locator('#fixture-enter').click();await winner.waitForURL('**/personal/');assert.equal(await winner.evaluate(()=>{const p=JSON.parse(sessionStorage.getItem('personal-gate-pass'));return p.expiresAt-p.issuedAt;}),3600000);
 const loser=await fixture([30,31,32,33,34]);for(const index of [0,2,4,6,8]){await loser.locator(`[data-index="${index}"]`).click();await loser.waitForTimeout(0);}assert.equal(await loser.locator('#gomoku-status').textContent(),'Panda won.');assert.ok(await loser.locator('#fixture-enter').isDisabled());await loser.locator('#rematch').click();assert.equal(await loser.locator('.gomoku-cell:not([data-stone="0"])').count(),0);assert.equal(await loser.locator('#gomoku-status').textContent(),'Your turn.');assert.ok(await loser.locator('#fixture-enter').isDisabled());
 const drawGroups=[[],[],[]];for(let r=0;r<15;r++)for(let c=0;c<15;c++)drawGroups[(r+2*c)%4<2?1:2].push(r*15+c);const draw=await fixture(drawGroups[2],drawGroups[1].length>drawGroups[2].length);for(const index of drawGroups[1]){await draw.locator(`[data-index="${index}"]`).click();}await draw.waitForFunction(()=>document.querySelector('#gomoku-status').textContent==='Draw.');assert.ok(await draw.locator('#fixture-enter').isDisabled());await draw.locator('#rematch').click();assert.equal(await draw.locator('.gomoku-cell:not([data-stone="0"])').count(),0);
 const mobile=await open(true);await mobile.locator('[data-index="113"]').tap();await mobile.waitForFunction(()=>document.querySelector('#game').dataset.phase==='human');assert.equal(await mobile.locator('.gomoku-cell[data-stone="1"]').count(),1);await mobile.screenshot({path:'/tmp/gomoku-mobile.png'});for(const width of [320,390,844]){await mobile.setViewportSize({width,height:width===844?390:844});assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await mobile.screenshot({path:'/tmp/gomoku-landscape.png'});
 assert.deepEqual(errors,[]);console.log('PASS real cloud Chromium worker/lazy loading, duplicate/illegal/keyboard, stale reset, worker retry, fake-adapter win/loss/draw/rematch and explicit one-hour entry, mobile touch/resize; no page errors. No physical phone tested.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
